name: Release to RubyGems

on:
  push:
    branches:
      - main
    paths:
      - 'lib/dns_record_updater/version.rb'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the gem
      run: gem build dns_record_updater.gemspec

    - name: Publish to RubyGems
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: gem push dns_record_updater-*.gem
